### ISSUE TITLE
NameError: global name 'onSysbotMentioned' is not defined

### ISSUE THREAD

**Issue by ombre8** [ombre8/jabberbot#12]
Bot failes sinces #11 

```Traceback (most recent call last):
  File "/home/lgrimm/.local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "jabberbot.py", line 91, in muc_message
    onSysbotMentioned(msg)
NameError: global name 'onSysbotMentioned' is not defined
ERROR    Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/home/lgrimm/.local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "jabberbot.py", line 91, in muc_message
    onSysbotMentioned(msg)
NameError: global name 'onSysbotMentioned' is not defined
DEBUG    SEND: <message to="sys@conference.puzzle.ch" type="error"><error type="cancel"><undefined-condition xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">SleekXMPP got into trouble.</text></error></message>
ERROR    global name 'onSysbotMentioned' is not defined
Traceback (most recent call last):
  File "/home/lgrimm/.local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "jabberbot.py", line 91, in muc_message
    onSysbotMentioned(msg)
NameError: global name 'onSysbotMentioned' is not defined
```

**Comment by id101010** [comment]
Fix: self.onSysbotMentioned :)
